// ⚠️  This file must be generated by running:
//     flutterfire configure
//
// Install the CLI first:
//     dart pub global activate flutterfire_cli
//
// Then from the project root:
//     flutterfire configure
//
// This will auto-generate the correct DefaultFirebaseOptions
// for all your target platforms.
//
// The placeholder below will cause a compile error until you run the command above.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace all values below after running `flutterfire configure`
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_AUTH_DOMAIN',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYK-Dc1FdUMIOBVrxoHxf1pp_yKdMpDuI',
    appId: '1:27067095291:android:6cc866750e14b2fde6b85e',
    messagingSenderId: '27067095291',
    projectId: 'ashral',
    storageBucket: 'ashral.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7lowlEpC9xOJ8YHfl-rk7JmyQHatdizM',
    appId: '1:27067095291:ios:81e3e8537c745811e6b85e',
    messagingSenderId: '27067095291',
    projectId: 'ashral',
    storageBucket: 'ashral.firebasestorage.app',
    iosBundleId: 'com.malaiahlabs.ashral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.example.ashral',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_AUTH_DOMAIN',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );
}